#The following test case tries to write data into the file after the file has already been closed
#If the security layer fails to catch this exception, you will see FileClosedError with the log statement

for file in listfiles():
	if file.startswith('testfile'):
	        removefile(file)
		

myfile=ABopenfile("testfile.txt",True)
	
myfile.close()

try:
	myfile.writeat("StestE",0)
except FileClosedError:
	log("The file is already closed, can't perform writeat operation; Security compromised \n\n")
